#!/bin/bash

function die {
    echo -e "\033[31m$(basename $0): ${1:-"Unknown Error"}\033[0m" 1>&2
    exit 1
}

function checkresult {
	if [ $? -ne 0 ]; then
		echo -e "\033[31m$(basename $0): failed!\033[0m" 1>&2
		exit 1
   	fi
}

# >>> installing packages

REPOS_PATH="/home/plux/Dropbox/Repositories"
ENV_PATH="$REPOS_PATH/environment-plux"

dpkg -i $ENV_PATH/programs/dwm-6.0/packages/*.deb
checkresult

dpkg -i $ENV_PATH/programs/dmenu-4.5/packages/*.deb
checkresult

dpkg -i $ENV_PATH/programs/st-0.4.1/packages/*.deb
checkresult

