#!/bin/bash

# external params file contains:
#	$SERVER - workstation ip to connect to
#	$USERNAME - workstation user name
#	$WIDTH - freerdp window width
#	$HEIGHT - freerdp window height
source rdpparams

echo -n "RDP password: "
read -s PASSWORD
echo

exec /usr/bin/xfreerdp \
/v:$SERVER \
/t:"Workstation RDP connection" \
/u:$USERNAME \
/p:$PASSWORD \
/w:$WIDTH \
/h:$HEIGHT \
-wallpaper \
-themes \
-sec-nla \
/cert-ignore \
#/f
