#!/bin/bash

if [ -x /usr/bin/kill ]; then
	KILL="/usr/bin/kill"
else
	KILL="/bin/kill"
fi

SIG=TERM
PIDS=$(pidof xfreerdp)

if [ -z "$PIDS" ]; then
	echo "no freerdp seesion is running"
	exit 1
fi

$KILL -$SIG $PIDS || {
	echo "$KILL failed. No sessions stopped"
	exit 1
}

exit 0
